---
# https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    allow-non-breakable-inline-mappings: true
    max: 140
    level: warning
  truthy: disable
  document-start: disable
  comments: disable
  braces: disable
  new-line-at-end-of-file: {}

ignore: |
  examples
  deployments
  vendor
